project:
  type: website
  output-dir: docs
  resources:
    - "projects/bariloche/images/slices/*.jpeg"
  

website:
  title: "Santiago Zuniga"
  favicon: favicon.svg
  navbar:
    logo: favicon.svg
    title: "Santiago Zúñiga"
    left:
      - href: index.qmd
        text: Home
      - href: projects/turbidity/index.qmd
        text: Multiscale CFD applied to buoyancy-driven flows
      - href: projects/bariloche/index.qmd
        text: Bariloche Urban Wind
      # - href: projects/cylinder/index.qmd
      #   text: Vortex-induced vibrations


format:
  html:
    theme: cosmo
    css: /styles.css
    toc: true
    lightbox: true